services:
  db:
    image: timescale/timescaledb:latest-pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_edge
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ecto://postgres:postgres@db:5432/weather_edge

volumes:
  pgdata:
